micronaut:
  server:
    port: 8080
  application:
    name: appModelo
  jms:
    sqs:
      enabled: true
      concurrency: 5-10
      message-to-prefetch: 100
  sqs:
    queue-name: "my-fila-queue"

datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://127.0.0.1:5433/dbexemple`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234567}
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true
netty:
  default:
    allocator:
      max-order: 3

services:
  aws:
    sqs:
      max-attemp-retries: 1